package com.aplivit.shared

import com.aplivit.core.domain.model.AppLanguage

data class AppStrings(
    val welcome: String,
    val resumeSession: String,
    val selectLevel: String,
    val nextLevel: String,
    val levelCompleted: String,
    val lockedLevel: String,
    val completedLabel: String,
    val availableLabel: String,
    val startGames: String,
    val verify: String,
    val reset: String,
    val speak: String,
    val stop: String,
    val listening: String,
    val correct: String,
    val tryAgain: String,
    val settings: String,
    val selectLanguage: String,
    val permissionNeeded: String,
    val dragDropInstruction: String,
    val dragDropSuccess: String,
    val selectionSuccess: String,
    val selectionError: String,
    val noSoundDetected: String,
    val recognitionError: String,
    val repeatError: String,
    val tapSyllableHint: String,
    val back: String,
    val learnToRead: String,
    val recapTitle: String,
    val levelIntro: String      // "Vamos a aprender la palabra" — used for TTS to avoid isolated syllable tokens
)

fun stringsFor(language: AppLanguage): AppStrings = when (language) {
    AppLanguage.SPANISH -> AppStrings(
        welcome = "Bienvenido. Empecemos desde el principio.",
        resumeSession = "Continuamos donde lo dejaste.",
        selectLevel = "Seleccioná un nivel para continuar.",
        nextLevel = "¡Muy bien! Seguimos con el siguiente nivel.",
        levelCompleted = "¡Muy bien! Completaste el nivel.",
        lockedLevel = "Bloqueado",
        completedLabel = "Completado",
        availableLabel = "Disponible",
        startGames = "Comenzar juegos",
        verify = "Verificar",
        reset = "Reiniciar",
        speak = "Hablar",
        stop = "Detener",
        listening = "Escuchando...",
        correct = "¡Correcto!",
        tryAgain = "Intentá nuevamente.",
        settings = "Configuración",
        selectLanguage = "Elegí tu idioma",
        permissionNeeded = "Se necesita permiso de micrófono para este ejercicio.",
        dragDropInstruction = "Arrastrá las sílabas para armar la palabra.",
        dragDropSuccess = "Muy bien. Ahora escuchá y elegí la sílaba correcta.",
        selectionSuccess = "Excelente. Ahora repetí lo que escuchás.",
        selectionError = "Eso no es correcto. Intentá de nuevo.",
        noSoundDetected = "No te escuché. Intentá de nuevo.",
        recognitionError = "Hubo un error. Intentá de nuevo.",
        repeatError = "No fue correcto. Intentá de nuevo.",
        tapSyllableHint = "Tocá cada sílaba para escucharla",
        back = "Volver",
        learnToRead = "Aprende a leer",
        recapTitle = "Repaso",
        levelIntro = "Vamos a aprender la palabra"
    )
    AppLanguage.ENGLISH -> AppStrings(
        welcome = "Welcome. Let's start from the beginning.",
        resumeSession = "Continuing where you left off.",
        selectLevel = "Select a level to continue.",
        nextLevel = "Great job! Let's continue with the next level.",
        levelCompleted = "Great job! You completed the level.",
        lockedLevel = "Locked",
        completedLabel = "Completed",
        availableLabel = "Available",
        startGames = "Start games",
        verify = "Verify",
        reset = "Reset",
        speak = "Speak",
        stop = "Stop",
        listening = "Listening...",
        correct = "Correct!",
        tryAgain = "Try again.",
        settings = "Settings",
        selectLanguage = "Choose your language",
        permissionNeeded = "Microphone permission is needed for this exercise.",
        dragDropInstruction = "Drag the syllables to form the word.",
        dragDropSuccess = "Great. Now listen and choose the correct syllable.",
        selectionSuccess = "Excellent. Now repeat what you hear.",
        selectionError = "That is not correct. Try again.",
        noSoundDetected = "I didn't hear you. Try again.",
        recognitionError = "There was an error. Try again.",
        repeatError = "That was not correct. Try again.",
        tapSyllableHint = "Tap each syllable to hear it",
        back = "Back",
        learnToRead = "Learn to read",
        recapTitle = "Review",
        levelIntro = "Let's learn the word"
    )
    AppLanguage.FRENCH -> AppStrings(
        welcome = "Bienvenue. Commençons depuis le début.",
        resumeSession = "Continuons là où tu t'es arrêté.",
        selectLevel = "Sélectionne un niveau pour continuer.",
        nextLevel = "Bravo ! Continuons avec le niveau suivant.",
        levelCompleted = "Bravo ! Tu as complété le niveau.",
        lockedLevel = "Bloqué",
        completedLabel = "Complété",
        availableLabel = "Disponible",
        startGames = "Commencer les jeux",
        verify = "Vérifier",
        reset = "Réinitialiser",
        speak = "Parler",
        stop = "Arrêter",
        listening = "Écoute en cours...",
        correct = "Correct !",
        tryAgain = "Réessaie.",
        settings = "Paramètres",
        selectLanguage = "Choisis ta langue",
        permissionNeeded = "Permission du microphone nécessaire pour cet exercice.",
        dragDropInstruction = "Fais glisser les syllabes pour former le mot.",
        dragDropSuccess = "Bien. Maintenant écoute et choisis la bonne syllabe.",
        selectionSuccess = "Excellent. Maintenant répète ce que tu entends.",
        selectionError = "Ce n'est pas correct. Réessaie.",
        noSoundDetected = "Je ne t'ai pas entendu. Réessaie.",
        recognitionError = "Il y a eu une erreur. Réessaie.",
        repeatError = "Ce n'était pas correct. Réessaie.",
        tapSyllableHint = "Appuie sur chaque syllabe pour l'entendre",
        back = "Retour",
        learnToRead = "Apprendre à lire",
        recapTitle = "Révision",
        levelIntro = "Apprenons le mot"
    )
}
